# 1 

In [2]:
# create a null vector / 1D array of size 10 and update fifth value to 11

In [3]:
import numpy as np
c = np.zeros(10)
print(c)
print("nilai ke 5 jadi 11")
c[5] = 11
print(c)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
nilai ke 5 jadi 11
[ 0.  0.  0.  0.  0. 11.  0.  0.  0.  0.]


# 2

In [9]:
#Write a NumPy program to create a 2x3 arrays and change it into 3x2 arrays

In [14]:
q = np.array([[1, 5, 8], [4, 7, 5]])
print(q)
print(q.shape)

[[1 5 8]
 [4 7 5]]
(2, 3)


In [15]:
z = np.reshape(q,(3,2))
print("Reshape 3x2:")
print(z)

Reshape 3x2:
[[1 5]
 [8 4]
 [7 5]]


# 3

In [8]:
#Write a NumPy program to create a 2d array with 1 on the border and 0 inside

In [16]:
d = np.ones((5,5))
print("create a 2d array with 1:")
print(d)
print("1 on the border and 0 inside :")
d[1:-1,1:-1] = 0
print(d)

create a 2d array with 1:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on the border and 0 inside :
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# 4

In [10]:
#Take a look at the following matrix. Access the [1, 1,2]

In [19]:
z = np.array([[[0, 1, 3],
               [5, 7, 9],
               [6, 8, 10]],
              
              [[0, 2, 4],
               [6, 8, 10],
               [0, 1, 3]],
             
              [[1, 1, 2],
               [5, 2, 9],
               [1, 3, 3]]])
print (z)
print(z.shape)

[[[ 0  1  3]
  [ 5  7  9]
  [ 6  8 10]]

 [[ 0  2  4]
  [ 6  8 10]
  [ 0  1  3]]

 [[ 1  1  2]
  [ 5  2  9]
  [ 1  3  3]]]
(3, 3, 3)


In [21]:
z[1,1,2]

10