# 1

In [1]:
# Create a 4x4 matrix with values ranging from 0 to 3

In [1]:
import numpy as np
a = np.zeros((4,4))
print("array:")
print(a)
print("values ranging from 0 to 3")
a += np.arange(4)
print(a)

 array:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Row values ranging from 0 to 3
[[0. 1. 2. 3.]
 [0. 1. 2. 3.]
 [0. 1. 2. 3.]
 [0. 1. 2. 3.]]


# 2

In [3]:
#Create and array with shape of 4x4 and turn it into two arrays along the second axis.

In [7]:
b = np.arange(16).reshape((4, 4))
print(b)
print("After splitting horizontally:")
print(np.hsplit(b, (2, 6)))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
After splitting horizontally:
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]]), array([], shape=(4, 0), dtype=int32)]
